base_config:
  device_ip: 172.22.76.25
  password: password
  username: admin
sensor_bandwidth:
  active_passive: 0
  poll_interval: 15
sensor_error:
  in_errors: 50
  out_errors: 60
  poll_interval: 30
sensor_mac:
  poll_interval: 30
sensor_traffic:
  poll_interval: 3600
sensor_utilisation:
  poll_interval: 30
  rx_threshold: 50
  tx_threshold: 50
