---
base_config:
  username: 'admin'
  password: 'password'
  base_url: 'http://172.24.86.228/rest'
sensor_traffic:
  poll_interval: 30
sensor_utilisation:
  poll_interval: 30
  metric_thresholds:
    in_unicast: 50
    out_unicast: 50
    in_multicast: 3
    out_multicast: 50
    in_broadcast: 50
    out_broadcast: 50
sensor_error:
  poll_interval: 30
  in_errors: 50
  out_errors: 60
