---
base_config:
  username: 'admin'
  password: 'password'
  device_ip: '172.24.86.228'
sensor_traffic:
  poll_interval: 30
sensor_utilisation:
  poll_interval: 30
  tx_threshold: 50
  rx_threshold: 50
sensor_error:
  poll_interval: 30
  in_errors: 50
  out_errors: 60
sensor_mac:
  poll_interval: 30
